url: https://kubernetes-charts.banzaicloud.com/charts/logging-operator-3.9.4.tgz
packageVersion: 01
releaseCandidateVersion: 00
additionalCharts:
  - workingDir: charts-crd
    crdOptions:
      templateDirectory: crd-template
      crdDirectory: templates
      addCRDValidationToMainChart: true
