{{- if .Values.elasticsearch.enabled }}
apiVersion: logging.banzaicloud.io/v1beta1
kind: ClusterFlow
metadata:
  name: {{ .Release.Name }}
  labels:
{{ include "logging-operator.labels" . | indent 4 }}
spec:
  outputRefs:
    - {{ .Release.Name }}-elasticsearch
{{- end }}
