apiVersion: logging.banzaicloud.io/v1beta1
kind: Logging
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "logging-operator.labels" . | indent 4 }}
spec:
  controlNamespace: {{ .Release.Namespace }}
  fluentbit: {}
  fluentd:
    disablePvc: {{ .Values.disablePvc }}
