{{- if and .Values.additionalLoggingSources.k3s.enabled (eq .Values.additionalLoggingSources.k3s.container_engine "systemd") }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-k3s
  labels:
{{ include "logging-operator.labels" . | indent 4 }}
data:
  fluent-bit.conf: |
    [SERVICE]
        Flush             1
        Grace             5
        Daemon            Off
        Log_Level         info
        Coro_Stack_Size   24576

    [INPUT]
        Name              systemd
        Tag               k3s
        Path              {{ .Values.systemdLogPath | default "/var/log/journal" }}
        Systemd_Filter    _SYSTEMD_UNIT=k3s.service

    [OUTPUT]
        Name              forward
        Match             *
        Host              {{ .Release.Name }}-fluentd.{{ .Release.Namespace }}.svc
        Port              24240
        Retry_Limit       False
{{- end }}
